INSERT INTO team(id,name,conference,division) VALUES (1,'Boston Bruins','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (2,'Buffalo Sabres','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (3,'Detroit Red Wings','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (4,'Florida Panthers','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (5,'Montreal Canadiens','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (6,'Ottawa Senators','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (7,'Tampa Bay Lightning','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (8,'Toronto Maple Leafs','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (9,'Carolina Hurricanes','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (10,'Columbus Blue Jackets','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (11,'New Jersey Devils','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (12,'New York Islanders','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (13,'New York Rangers','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (14,'Philadelphia Flyers','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (15,'Pittsburgh Penguins','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (16,'Washington Capitals','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (17,'Anaheim Ducks','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (18,'Arizona Coyotes','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (19,'Calgary Flames','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (20,'Edmonton Oilers','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (21,'Los Angeles Kings','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (22,'San Jose Sharks','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (23,'Vancouver Canucks','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (24,'Vegas Golden Knights','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (25,'Chicago Blackhawks','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (26,'Colorado Avalanche','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (27,'Dallas Stars','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (28,'Minnesota Wild','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (29,'Nashville Predators','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (30,'St. Louis Blues','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (31,'Winnipeg Jets','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (100,'Team Atlantic','Eastern','Atlantic');
INSERT INTO team(id,name,conference,division) VALUES (101,'Team Metropolitan','Eastern','Metropolitan');
INSERT INTO team(id,name,conference,division) VALUES (102,'Team Pacific','Western','Pacific');
INSERT INTO team(id,name,conference,division) VALUES (103,'Team Central','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (104,'Team Toews','Western','Central');
INSERT INTO team(id,name,conference,division) VALUES (105,'Team Foligno','Western','Central');

